// AUTO-GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Run `npm run build-gallery` after adding photos to public/images/mariachi_photos.
export interface GalleryPhoto { src: string; w: number; h: number; alt: string; kind: "group" | "member"; }

export const gallery: GalleryPhoto[] = [
  {
    "src": "/images/mariachi_photos/mariachi_main.png",
    "w": 1440,
    "h": 870,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_1.png",
    "w": 2246,
    "h": 1288,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_10.png",
    "w": 2388,
    "h": 1294,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_11.png",
    "w": 1510,
    "h": 958,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_12.png",
    "w": 1536,
    "h": 1100,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_13.png",
    "w": 1088,
    "h": 966,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_14.png",
    "w": 1188,
    "h": 1240,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_15.png",
    "w": 996,
    "h": 1168,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_16.png",
    "w": 1420,
    "h": 1154,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_17.png",
    "w": 1278,
    "h": 972,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_18.png",
    "w": 1404,
    "h": 778,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_19.png",
    "w": 1458,
    "h": 836,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_2.png",
    "w": 2200,
    "h": 1466,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_20.png",
    "w": 1334,
    "h": 898,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_21.png",
    "w": 1430,
    "h": 924,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_22.png",
    "w": 1314,
    "h": 938,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_23.png",
    "w": 1432,
    "h": 1098,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_24.png",
    "w": 1508,
    "h": 964,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_25.png",
    "w": 1426,
    "h": 820,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_26.png",
    "w": 1448,
    "h": 768,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_27.png",
    "w": 1354,
    "h": 960,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_28.png",
    "w": 1448,
    "h": 1004,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_29.png",
    "w": 1340,
    "h": 776,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_3.png",
    "w": 1506,
    "h": 1050,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_30.png",
    "w": 1504,
    "h": 852,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_31.png",
    "w": 1396,
    "h": 1114,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_32.png",
    "w": 1464,
    "h": 812,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_33.png",
    "w": 1270,
    "h": 746,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_34.png",
    "w": 1092,
    "h": 1222,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_35.png",
    "w": 1320,
    "h": 816,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_36.png",
    "w": 1456,
    "h": 690,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_37.png",
    "w": 1294,
    "h": 858,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_38.png",
    "w": 1220,
    "h": 912,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_4.png",
    "w": 2266,
    "h": 1296,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_5.png",
    "w": 1924,
    "h": 1260,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_6.png",
    "w": 1824,
    "h": 1278,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_7.png",
    "w": 1882,
    "h": 1170,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_8.png",
    "w": 1848,
    "h": 1192,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  },
  {
    "src": "/images/mariachi_photos/photo_9.png",
    "w": 1502,
    "h": 974,
    "alt": "NYU Mariachi performance",
    "kind": "group"
  }
];
