// AUTO-GENERATED by scripts/build-roster.mjs — do not edit by hand.
// Run `npm run build-roster` after changing photos in public/images/roster.
import type { Semester } from "@/lib/types";

export const SECTION_LABELS: Record<string, string> = {
  "armonia": "Armonía",
  "violins": "Violins",
  "woodwind_brass": "Woodwind & Brass",
  "vocalists": "Vocalists"
};

export const roster: Semester[] = [
  {
    "id": "spring_2026",
    "label": "Spring 2026",
    "current": true,
    "members": [
      {
        "name": "Ana",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/ana_flute.png"
      },
      {
        "name": "Chris",
        "section": "armonia",
        "instruments": [
          "Vihuela"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/chris_vihuela.png"
      },
      {
        "name": "Clarissa",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/violins/clarissa_violins.png"
      },
      {
        "name": "Diego",
        "section": "armonia",
        "instruments": [
          "Guitarrón"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/diego_guitarron.png"
      },
      {
        "name": "Eric",
        "section": "woodwind_brass",
        "instruments": [
          "Soprano Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/eric_sopranosax.png"
      },
      {
        "name": "Erik",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/erik_flute.png"
      },
      {
        "name": "Honglin",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/violins/honglin_violins.png"
      },
      {
        "name": "Ian",
        "section": "woodwind_brass",
        "instruments": [
          "Alto Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/ian_altosax.png"
      },
      {
        "name": "Isabella",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/isabella_trumpet.png"
      },
      {
        "name": "Jazmeen",
        "section": "armonia",
        "instruments": [
          "Guitar",
          "Vocals",
          "Vihuela"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2026/armonia/jazmeen_guitar-singer-vihuela.png"
      },
      {
        "name": "Jerry",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/jerry_guitar.png"
      },
      {
        "name": "Jose",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/jose_guitar.png"
      },
      {
        "name": "Justin",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/justin_trumpet.png"
      },
      {
        "name": "Leo",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/leo_guitar.png"
      },
      {
        "name": "Lizzy",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/lizzy_guitar.png"
      },
      {
        "name": "Mannu",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/violins/mannu_violins.png"
      },
      {
        "name": "Susie",
        "section": "armonia",
        "instruments": [
          "Harp"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/armonia/susie_harp.png"
      },
      {
        "name": "Victoria",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/violins/victoria_violins.png"
      },
      {
        "name": "Zoya",
        "section": "woodwind_brass",
        "instruments": [
          "Alto Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2026/woodwind_brass/zoya_altosax.png"
      }
    ]
  },
  {
    "id": "fall_2025",
    "label": "Fall 2025",
    "current": false,
    "members": [
      {
        "name": "Abi",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/abi_flute.png"
      },
      {
        "name": "Ana",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/ana_flute.png"
      },
      {
        "name": "Chris",
        "section": "armonia",
        "instruments": [
          "Vihuela"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/chris_vihuela.png"
      },
      {
        "name": "Clarrisa",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/violins/clarrisa_violin.png"
      },
      {
        "name": "Cody",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/violins/cody_violin.png"
      },
      {
        "name": "Diego",
        "section": "armonia",
        "instruments": [
          "Guitarrón"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/diego_guitarron.png"
      },
      {
        "name": "Eric",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/eric_guitar.png"
      },
      {
        "name": "Eric",
        "section": "woodwind_brass",
        "instruments": [
          "Soprano Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/eric_sopranosax.png"
      },
      {
        "name": "Honglin",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/violins/honglin_violin.png"
      },
      {
        "name": "Ivy",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/violins/ivy_violin.png"
      },
      {
        "name": "Jerry",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/jerry_guitar.png"
      },
      {
        "name": "Jose",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/jose_guitar.png"
      },
      {
        "name": "Joshua",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/joshua_trumpet.png"
      },
      {
        "name": "Leo",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/leo_guitar.png"
      },
      {
        "name": "Lizzy",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/lizzy_guitar.png"
      },
      {
        "name": "Manny",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/violins/manny_violin.png"
      },
      {
        "name": "Raka",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/raka_flute.png"
      },
      {
        "name": "Rebecca",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/rebecca_trumpet.png"
      },
      {
        "name": "Tom",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/armonia/tom_guitar.png"
      },
      {
        "name": "Victoria",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/violins/victoria_violin.png"
      },
      {
        "name": "Zoya",
        "section": "woodwind_brass",
        "instruments": [
          "Alto Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2025/woodwind_brass/zoya_altosax.png"
      }
    ]
  },
  {
    "id": "spring_2025",
    "label": "Spring 2025",
    "current": false,
    "members": [
      {
        "name": "Aaron",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/aaron_trumpet.png"
      },
      {
        "name": "Abi",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/abi_flute.png"
      },
      {
        "name": "Alex",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/violins/alex_violins.png"
      },
      {
        "name": "Ana",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/ana_flute.png"
      },
      {
        "name": "Anahi",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/anahi_guitar.png"
      },
      {
        "name": "Angel",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/angel_guitar.png"
      },
      {
        "name": "Aria",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/violins/aria_violins.png"
      },
      {
        "name": "Chris",
        "section": "armonia",
        "instruments": [
          "Vihuela"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/chris_vihuela.png"
      },
      {
        "name": "Diego",
        "section": "armonia",
        "instruments": [
          "Guitarrón"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/diego_guitarron.png"
      },
      {
        "name": "Eric",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/eric_guitar.png"
      },
      {
        "name": "Eric",
        "section": "woodwind_brass",
        "instruments": [
          "Soprano Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/eric_sopranosax.png"
      },
      {
        "name": "Henry",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/henry_trumpet.png"
      },
      {
        "name": "Ivy",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/violins/ivy_violins.png"
      },
      {
        "name": "Jose",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/jose_guitar.png"
      },
      {
        "name": "Joshua",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/joshua_trumpet.png"
      },
      {
        "name": "Kalsey",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/kalsey_flute.png"
      },
      {
        "name": "Lizzy",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/lizzy_guitar.png"
      },
      {
        "name": "Miranda",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/miranda_guitar.png"
      },
      {
        "name": "Rayan",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/rayan_guitar.png"
      },
      {
        "name": "Rhan",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/rhan_guitar.png"
      },
      {
        "name": "Ricardo",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/ricardo_guitar.png"
      },
      {
        "name": "Thomas",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/armonia/thomas_guitar.png"
      },
      {
        "name": "Zoya",
        "section": "woodwind_brass",
        "instruments": [
          "Alto Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2025/woodwind_brass/zoya_altosax.png"
      }
    ]
  },
  {
    "id": "fall_2024",
    "label": "Fall 2024",
    "current": false,
    "members": [
      {
        "name": "Aaron",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/woodwind_brass/aaron_trumpet.png"
      },
      {
        "name": "Abi",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/woodwind_brass/abi_flute.png"
      },
      {
        "name": "Alex",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/violins/alex_violins.png"
      },
      {
        "name": "Anahi",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/anahi_guitar.png"
      },
      {
        "name": "Aria",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/violins/aria_violins.png"
      },
      {
        "name": "Chris",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/chris_guitar.png"
      },
      {
        "name": "Clarissa",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/violins/clarissa_violins.png"
      },
      {
        "name": "Diego",
        "section": "armonia",
        "instruments": [
          "Guitarrón"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/diego_guitarron.png"
      },
      {
        "name": "Eric",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/eric_guitar.png"
      },
      {
        "name": "Eric",
        "section": "woodwind_brass",
        "instruments": [
          "Soprano Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/woodwind_brass/eric_supranosax.png"
      },
      {
        "name": "Genesis",
        "section": "armonia",
        "instruments": [
          "Guitarrón"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/genesis_guitarron.png"
      },
      {
        "name": "Henry",
        "section": "woodwind_brass",
        "instruments": [
          "Trombone",
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/woodwind_brass/henry_trombone-trumpet.png"
      },
      {
        "name": "Jose",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/jose_guitar.png"
      },
      {
        "name": "Kalsey",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/woodwind_brass/kalsey_flute.png"
      },
      {
        "name": "Maryangel",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/maryangel_guitar.png"
      },
      {
        "name": "Paola",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/fall_2024/vocalists/paola_singer.png"
      },
      {
        "name": "Rayan",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/rayan_guitar.png"
      },
      {
        "name": "Rhan",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/rhan_guitar.png"
      },
      {
        "name": "Ricardo",
        "section": "armonia",
        "instruments": [
          "Vihuela"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/ricardo_vihuela.png"
      },
      {
        "name": "Thomas",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/armonia/thomas_guitar.png"
      },
      {
        "name": "Victoria",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/violins/victoria_violins.png"
      },
      {
        "name": "Zoya",
        "section": "woodwind_brass",
        "instruments": [
          "Alto Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/fall_2024/woodwind_brass/zoya_altosax.png"
      }
    ]
  },
  {
    "id": "spring_2024",
    "label": "Spring 2024",
    "current": false,
    "members": [
      {
        "name": "Aaron",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/aaron_trumpet.png"
      },
      {
        "name": "Anahi",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2024/vocalists/anahi_singer.png"
      },
      {
        "name": "Aria",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/violins/aria_violins.png"
      },
      {
        "name": "Avi",
        "section": "woodwind_brass",
        "instruments": [
          "Trumpet"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/avi_trumpet.png"
      },
      {
        "name": "Clarissa",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/violins/clarissa_violins.png"
      },
      {
        "name": "Diego",
        "section": "armonia",
        "instruments": [
          "Guitarrón"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/armonia/diego_guitarron.png"
      },
      {
        "name": "Eric",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2024/vocalists/eric_singer.png"
      },
      {
        "name": "Eric",
        "section": "woodwind_brass",
        "instruments": [
          "Alto Sax"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/eric_altosax.png"
      },
      {
        "name": "Grey",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/grey_flute.png"
      },
      {
        "name": "Henry",
        "section": "woodwind_brass",
        "instruments": [
          "Trombone"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/henry_trumbone.png"
      },
      {
        "name": "Jaden",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/armonia/jaden_guitar.png"
      },
      {
        "name": "Jair",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2024/vocalists/jair_singer.png"
      },
      {
        "name": "Jair",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/jair_flute.png"
      },
      {
        "name": "Jose",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2024/vocalists/jose_singer.png"
      },
      {
        "name": "Kalsey",
        "section": "woodwind_brass",
        "instruments": [
          "Flute"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/woodwind_brass/kalsey_flute.png"
      },
      {
        "name": "Paola",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2024/vocalists/paola_singer.png"
      },
      {
        "name": "Rayan",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/armonia/rayan_guitar.png"
      },
      {
        "name": "Ricardo",
        "section": "armonia",
        "instruments": [
          "Vihuela"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/armonia/ricardo_vihuela.png"
      },
      {
        "name": "Samuel",
        "section": "violins",
        "instruments": [
          "Violin"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/violins/samuel_violins.png"
      },
      {
        "name": "Thomas",
        "section": "armonia",
        "instruments": [
          "Guitar"
        ],
        "isVocalist": false,
        "photo": "/images/roster/spring_2024/armonia/thomas_guitar.png"
      },
      {
        "name": "Yailyn",
        "section": "vocalists",
        "instruments": [
          "Vocals"
        ],
        "isVocalist": true,
        "photo": "/images/roster/spring_2024/vocalists/yailyn_singer.png"
      }
    ]
  }
];
