// Scans public/images/roster/<semester>/<section>/<name>_<instrument>.png
// and writes src/content/roster.ts. Run: npm run build-roster
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(process.cwd(), "public", "images", "roster");
const OUT = join(process.cwd(), "src", "content", "roster.ts");

const SECTION_LABEL = {
  armonia: "Armonía",
  violins: "Violins",
  woodwind_brass: "Woodwind & Brass",
  vocalists: "Vocalists",
};

const INSTRUMENT_LABEL = {
  guitar: "Guitar", vihuela: "Vihuela", guitarron: "Guitarrón", harp: "Harp",
  violin: "Violin", violins: "Violin", trumpet: "Trumpet", trombone: "Trombone",
  trumbone: "Trombone", flute: "Flute", altosax: "Alto Sax", sopranosax: "Soprano Sax",
  supranosax: "Soprano Sax", singer: "Vocals",
};

const titleCase = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const prettyInstrument = (raw) => INSTRUMENT_LABEL[raw] ?? titleCase(raw);
const prettySemester = (id) => {
  const [term, year] = id.split("_");
  return `${titleCase(term)} ${year}`;
};

function dirs(p) {
  try { return readdirSync(p).filter((d) => statSync(join(p, d)).isDirectory()); }
  catch { return []; }
}
function files(p) {
  try { return readdirSync(p).filter((f) => /\.(png|jpe?g|webp)$/i.test(f)); }
  catch { return []; }
}

// order newest first
const TERM_ORDER = { spring: 1, fall: 2 };
const semesters = dirs(ROOT).sort((a, b) => {
  const [ta, ya] = a.split("_"); const [tb, yb] = b.split("_");
  if (yb !== ya) return Number(yb) - Number(ya);
  return (TERM_ORDER[tb] ?? 0) - (TERM_ORDER[ta] ?? 0);
});

const data = semesters.map((semId, i) => {
  const sections = dirs(join(ROOT, semId));
  const members = [];
  for (const section of sections) {
    for (const file of files(join(ROOT, semId, section))) {
      const stem = file.replace(/\.[^.]+$/, "");
      const [namePart, instrPart = ""] = stem.split(/_(.+)/);
      const instruments = instrPart.split("-").filter(Boolean).map(prettyInstrument);
      const name = titleCase(namePart);
      members.push({
        name,
        section,
        instruments: instruments.length ? instruments : ["Member"],
        isVocalist: /singer|vocal/i.test(instrPart),
        photo: `/images/roster/${semId}/${section}/${file}`,
      });
    }
  }
  members.sort((a, b) => a.name.localeCompare(b.name));
  return { id: semId, label: prettySemester(semId), current: i === 0, members };
});

const header = `// AUTO-GENERATED by scripts/build-roster.mjs — do not edit by hand.
// Run \`npm run build-roster\` after changing photos in public/images/roster.
import type { Semester } from "@/lib/types";

export const SECTION_LABELS: Record<string, string> = ${JSON.stringify(SECTION_LABEL, null, 2)};

export const roster: Semester[] = `;

writeFileSync(OUT, header + JSON.stringify(data, null, 2) + ";\n");
console.log(`Wrote ${OUT} — ${data.length} semesters, ${data.reduce((n, s) => n + s.members.length, 0)} members.`);
