// Scans every photo in public/images (group photos + all member headshots),
// reads real PNG dimensions, and writes src/content/gallery.ts for the Media
// collage. Group shots are interleaved among headshots for visual variety.
// Run: npm run build-gallery
import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PUB = join(process.cwd(), "public");
const GROUP_DIR = join(PUB, "images", "mariachi_photos");
const ROSTER_DIR = join(PUB, "images", "roster");
const OUT = join(process.cwd(), "src", "content", "gallery.ts");

// Read width/height from a PNG IHDR header without any dependency.
function pngSize(absPath) {
  try {
    const buf = readFileSync(absPath).subarray(0, 24);
    const isPng = buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47;
    if (!isPng) return { w: 1000, h: 1000 };
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
  } catch {
    return { w: 1000, h: 1000 };
  }
}

const titleCase = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const files = (p) => {
  try { return readdirSync(p).filter((f) => /\.png$/i.test(f)); }
  catch { return []; }
};
const dirs = (p) => {
  try { return readdirSync(p).filter((d) => statSync(join(p, d)).isDirectory()); }
  catch { return []; }
};

// Group / performance photos
const group = files(GROUP_DIR).map((f) => {
  const { w, h } = pngSize(join(GROUP_DIR, f));
  return { src: `/images/mariachi_photos/${f}`, w, h, alt: "NYU Mariachi performance", kind: "group" };
});

// Only the group / performance photos in mariachi_photos/ — member headshots
// are intentionally excluded from the collage (they live on /members).
const out = group;

const header = `// AUTO-GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Run \`npm run build-gallery\` after adding photos to public/images/mariachi_photos.
export interface GalleryPhoto { src: string; w: number; h: number; alt: string; kind: "group" | "member"; }

export const gallery: GalleryPhoto[] = `;

writeFileSync(OUT, header + JSON.stringify(out, null, 2) + ";\n");
console.log(`Wrote ${OUT} — ${out.length} group photos.`);
